version: '3'

services:
  # postgres:
  #   image: "postgres"
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_PASSWORD: "admin"
  #     POSTGRES_DB: "postgres"
  #   volumes: 
  #   - /var/lib/postgresql/data:/var/lib/posgresql/data/
  #   ports:
  #   - 5432:5432

  # pgadmin: 
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #   ports:
  #     - 9876:80

  docker run -d --name elasticsearch -e discovery.type=single-node -e bootstrap.memory_lock=true -e "ES_JAVA_OPTS=-Xmx512m -Xmx512m" -p 9200:9200 --net teste -v /home/vitor/Desktop/devcontainer/elasticsearch/data:/usr/share/elasticsearch/data elasticsearch:7.16.3

  docker run -d --name kibana --net teste -e ELASTICSEARCH_HOSTS="http://elasticsearch:9200" -p 5601:5601 kibana:7.16.3

    
