version: '3'

services:    
  elasticsearch:
      image: elasticsearch:7.16.3
      container_name: elasticsearch
      environment:
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      volumes:
        - ../elasticsearch/data:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
      networks:
        - teste

  kibana:
    image: kibana:7.16.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS="http://elasticsearch:9200"
    volumes:
      - ../config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - teste
    

networks:
  teste: 
    external: true